messages:
  scheduler_today:
    header: "おはようございます。%1$d月%2$d日%3$s曜日でございます。"
    footer: "本日もどうぞよろしくお願いいたします。"
    schedule:
      header: "本日のご予定をお知らせいたします。"
      footer: "以上でございます。"
      timetable: "%1$sより %2$s %3$s"
      overday: "%1$s %2$s"
      banner: "%1$s %2$s"
    first_of_year:
      header: "あけましておめでとうございます。新しい年を迎えることができまして、大変喜ばしく思います。%d年でございます。"
      footer: "今年もまた一年、どうぞよろしくお願いいたします。"
    last_of_year:
      footer:
      - "今年の出勤日も本日が最後となりました。"
      - "わたくしの今年の業務も、この通知で終了でございます。"
      - "一年間お疲れ様でございました。良いお年をお迎えください。"
    tokyodome:
      message: "東京ドームでは %1$s %2$s が開催されますので、お出かけの際はご注意ください。"
      close_message: "東京ドームは本日 %1$s でございます。"
    cityhall:
      message: "東京ドームシティホールでは %1$s が開催されますので、お出かけの際はご注意ください。詳細は %2$s をご覧下さい。"
  before_period:
    header:
    - "まもなく19時、業務終了のお時間でございます。"
    - "まもなく業務終了のお時間でございます。"
    - "業務終了のお時間がせまっております。"
    footer: []
    middle:
    - probability: 100
      messages:
      - "お帰りの前に本日のお仕事を振り返るのはいかがでしょうか。\nhttps://feedforce.qiita.com/"
    tokyodome:
      message: "東京ドームでは %1$s %2$s 開催でございます。お帰りのお時間にはお気をつけ下さい。"
      close_message: "東京ドームは本日 %1$s でございます。"
    cityhall:
      message: "東京ドームシティホールでは %1$s 開催でございます。お出かけの際はご注意ください。詳細は %2$s をご覧下さい。"
  period:
    header:
    - "本日も19時をまわりまして、業務終了のお時間でございます。"
    - "19時をお知らせにあがりました、業務終了のお時間でございます。"
    - "皆様、本日の業務時間は終了でございます。"
    footer: []
    middle:
    - probability: 100
      messages:
      - "どうぞお忘れ物などなさいませんよう。"
      - "あまりご無理はなさらず、お体をお休めください。"
      - "本日もお疲れさまでございました。"
    friday:
    - "どうぞ良い週末をお過ごしください。"
    - "心穏やかな週末になるよう、お祈り申し上げます。"
    power_failure:
    - "次の出社までの間に停電の予定がございます。お帰りの際に電源の状態をご確認ください。"
